// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'error': string;
  'fadeClose': string;
  'fadeIn': string;
  'info': string;
  'message': string;
  'row': string;
  'runRow': string;
  'success': string;
  'toast': string;
  'warning': string;
}
export const cssExports: CssExports;
export default cssExports;
